### ISSUE TITLE
Load API KEY from environment variables

### ISSUE THREAD

**Issue by plaindocs** [ayastreb/jekyll-maps#19]
If you've got an your config in a public repo - putting the API_KEY in the jekyll conf is not a good idea.

I can't find an easy way to load environment variables into the config. Loading them into pages is easier (https://gist.github.com/biilmann/5dc7bac1bab97759b7e93e9954b021a2).

**Comment by plaindocs** [comment]
Update, I'm pretty sure that if you add an edited version of that plugin to the gemfile:

```ruby
module Jekyll
  class EnvironmentVariablesGenerator < Generator
    def generate(site)
      site.config['gmaps_api_key'] = ENV['gmaps_api_key']
    end
  end
end
```

and change `https://github.com/ayastreb/jekyll-maps/blob/a8b028f285fe7f3e4a51077fc881e9f28ef37f1a/lib/jekyll-maps/google_map_api.rb#L30`

to something along the lines of

```ruby
api_key = @config.fetch("site", {})
	            .fetch("gmaps_api_key", "")
```

It should work.

**Comment by ayastreb** [comment]
btw, is API key considered secret? it is inserted in HTML anyways :)
as far as I know you can restrict who can access your API key in Google Developer Console

**Comment by plaindocs** [comment]
Heh, I was looking at a few API keys, some of which definitely were secret. If this maps one is in the html then we can forget the PR I think.

**Comment by ayastreb** [comment]
Ok, I'll close it :) Thanks for bringing it up anyway 👍
