### ISSUE TITLE
Uknown tag error

### ISSUE THREAD

**Issue by bonobo** [ayastreb/jekyll-maps#21]
Hi,

I've tried to install your plugin to my site, I followed instructions in README (add gem into Gemfile and also _config), but when building I get error Liquid syntax error unknown tag google_maps.

Thanks for your help.

**Comment by ayastreb** [comment]
Hi @bonobo 
did you install gems (`bundle install`) ? Can you show a list of installed gems (output of `gem list | grep jekyll`) ?

**Comment by bonobo** [comment]
Yes I installed gems, here is output of gem list:
`$ gem list | grep jekyll`
`jekyll (3.4.0)`
`jekyll-feed (0.9.1)`
`jekyll-maps (2.0.0)`
`jekyll-sass-converter (1.5.0)`  
`jekyll-watch (1.5.0)` 
`jekyll-youtube (1.0.0)`

**Comment by ayastreb** [comment]
Hi @bonobo 
sorry for late reply :(
Can you provide the source code where you use `google_maps` tag?

**Comment by bonobo** [comment]
Hi @ayastreb  here it is [https://github.com/bonobo/bonobo.github.io/blob/master/about/index.md](url)
I just used location from your install guide for example.

**Comment by ayastreb** [comment]
ok, now I see it :) you've got `gem` section twice in your `_config.xml`:
```
gems:
  - jekyll-feed
  - jekyll-maps
  # - flickraw
gems: [jekyll-youtube]
```
and second one overrides the first one. Just change it to
```
gems:
  - jekyll-feed
  - jekyll-maps
  - jekyll-youtube
```
and it should work 👍

**Comment by bonobo** [comment]
Thank you very much, I just started with jekyll so I am learning every day. :)
