### ISSUE TITLE
Filter doesn't work if string has spaces

### ISSUE THREAD

**Issue by acurley** [ayastreb/jekyll-maps#25]
For some reason the filter function doesn't work if there are spaces. For example, `foo="bar baz"` would not filter a collection whose front matter had `foo: bar baz`.

**Comment by ayastreb** [comment]
Hi @acurley 
thanks for reporting it! Fixed in 2.0.2

**Comment by acurley** [comment]
Thanks for getting to it so quickly! I wasn't sure if remove the \s would break a whole bunch of other things but seemingly not.  Thanks!
