### ISSUE TITLE
Support for OSM

### ISSUE THREAD

**Issue by PascalBru** [ayastreb/jekyll-maps#27]
Are you planning to support also OSM Maps?

**Comment by ayastreb** [comment]
Hi,
sorry, I don't have the capacity at the moment to work on OSM support 😞 
Also I don't have much experience with OSM, but PRs are always welcome 👍

**Comment by PascalBru** [comment]
THX for quick reply. 
Perhaps I will have a look at it and send an PR

**Comment by rriemann** [comment]
Hey @PascalBru , I'm thinking of adding mapbox support. Have you worked on OSM support?

**Comment by rriemann** [comment]
With only a 12 month delay, I have started today to work on a pull request allowing for mapbox support. mapbox uses OSM data.
