### ISSUE TITLE
Generated links don't respect baseurl in _config.yml

### ISSUE THREAD

**Issue by fraz3alpha** [ayastreb/jekyll-maps#28]
I have used this plugin in a GitHub pages project repository, but the links generated from the map don't include the subfolder that my site is served in, it always reference the root.

I feel the plugin should be pulling this automatically from the main `_config.yml` configuration file, but is there is plugin-specific configuration setting I should be setting instead? - or is this indeed not supported at the moment?

**Comment by ayastreb** [comment]
Thanks for reporting! I will check in the next couple of days

**Comment by ayastreb** [comment]
Please, try with jekyll-maps 2.1.0 - should be fixed now.

**Comment by fraz3alpha** [comment]
Looks good to me 👍, many thanks for fixing this!
