### ISSUE TITLE
Liquid syntax error: unknown tag 'google_map'

### ISSUE THREAD

**Issue by song85129** [ayastreb/jekyll-maps#29]
Hi, I was trying to put map in my site. I was following your steps. But it keeps saying Liquid Exception: Liquid syntax error (line 44): Unknown tag 'google_map'.
Does anyone encounter this before?

**Comment by ayastreb** [comment]
Hi! Have you checked #21 ? Did you install the plugin with bundler?

**Comment by song85129** [comment]
@ayastreb Hi, thank you for your superfast reply, Yes I have checked it. I installed plugin with bundler and I can see it with : `gem list | grep jekyll`, it gaves: jekyll-maps (2.0.4)

I also double checked my _config.yml:
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-maps
  - jekyll-gist
  - jekyll-feed
  - jemoji
there is no other plugins session in the file.

Btw , Happy new year

**Comment by ayastreb** [comment]
Happy new year!)

Do you have the source code of your site available online? Can I check?

**Comment by song85129** [comment]
@ayastreb  Hi, sorry for the late reply. The repo is private I can't share you here. I used the embed map instead to make it work.
